services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trainstation
      POSTGRES_USER: trainuser
      POSTGRES_PASSWORD: trainpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    command: sh -c "./wait-for-db.sh db python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
